---
init_cluster_pod_network_cidr: "10.100.0.0/16"
init_cluster_service_network_cidr: "10.44.0.0/16"
init_cluster_apiserver_cert_extra_sans: []
init_cluster_skip_kube_proxy: true
init_cluster_setup_kubeconfig_on_lb: true
