---
encrypt_etcd_at_rest_apiserver_timeout: 60
encrypt_etcd_at_rest_encrypted_resources:
  - secrets
encrypt_etcd_at_rest_encryption_providers:
  - secretbox:
      keys:
        - name: key1
          secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
  - identity: {}
