---
# Get control plane endpoint if there's more than one control plane node defined
# Init config template checks if control_plane_endpoint var is defined and adds required fields

- name: Set configuration variables
  ansible.builtin.set_fact:
    init_cluster_multiple_control_plane_nodes: "{{ groups['control_plane_nodes'] | length > 1 }}"
    init_cluster_external_etcd: "{{ groups['etcd_nodes'] | length > 1 }}"

- name: Set control plane endpoint
  ansible.builtin.set_fact:
    init_cluster_control_plane_endpoint: "{{ hostvars[groups['lb_node'][0]]['ansible_host'] }}"
  when: init_cluster_multiple_control_plane_nodes

- name: Copy cert files from external etcd node
  when: init_cluster_external_etcd
  block:
    - name: Ensure pki/etcd directory exists
      ansible.builtin.file:
        path: /etc/kubernetes/pki/etcd
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy etcd certs to control plane node
      ansible.builtin.copy:
        src: "{{ etcd_cert_dir }}/{{ item }}"
        dest: "/etc/kubernetes/pki/{{ item }}"
        owner: root
        group: root
        mode: "0755"
      loop:
        - etcd/ca.crt
        - apiserver-etcd-client.crt
        - apiserver-etcd-client.key

# Create init config file from template
- name: Create init config file
  ansible.builtin.template:
    src: kubeadm-init-config-template.j2
    dest: /tmp/kubeadm-init-config.yaml
    owner: root
    group: root
    mode: "0755"

- name: Run kubeadm init on primary control plane node
  ansible.builtin.command:
    cmd: kubeadm init --config /tmp/kubeadm-init-config.yaml --upload-certs
  changed_when: false
  register: init_cluster_kubeadm_init_output

## Get certficate key for joining other control plane nodes
## Note! No longer needed. New certificate is generated and uploaded during join_control in order to decouple init_cluster and join_cluster roles

# - ansible.builtin.set_fact:
#     cert_key: "{{ init_cluster_kubeadm_init_output.stdout | regex_findall('--certificate-key\\s+([0-9a-fA-F]+)\\s+') | first | default('') }}"
#   when: multiple_control_plane_nodes
#   run_once: true

- name: Setup kubeconfig foor root and ansible user
  ansible.builtin.include_role:
    name: common_utils
    tasks_from: setup_kubeconfig.yaml

- name: Get loadbalancer node if available
  ansible.builtin.set_fact:
    init_cluster_lb_node: "{{ groups['lb_node'] | default([]) | first | default('NA') }}"

- name: Setup kubeconfig on lb node
  when: init_cluster_setup_kubeconfig_on_lb and init_cluster_multiple_control_plane_nodes
  block:
    # Create ~/.kube dir for ansible user used in lb node
    - name: Create directory for kubeconfig on loadbalancer node
      become: false
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0775"
      delegate_to: "{{ init_cluster_lb_node }}"

    # Copy /etc/kubernetes/admin.conf from control plane node to ~/.kube/config on lb node
    - name: Copy admin.conf from primary control plane node to local machine
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/
        flat: true

    - name: Copy admin.conf from local to loadbalancer node
      become: false
      ansible.builtin.copy:
        src: /tmp/admin.conf
        dest: ~/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0775"
      delegate_to: "{{ init_cluster_lb_node }}"

    - name: Remove admin.conf from localhost
      ansible.builtin.file:
        path: /tmp/admin.conf
        state: absent
      delegate_to: localhost
