---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

# 1. Configure the kubelet to be a service manager for etcd. Do this in all the etcd cluster nodes.

- name: Ensure /etc/systemd/system/kubelet.service.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: Copy KubeletConfiguration and service manager configuration files to etcd host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/kubelet.service.d/{{ item }}"
  loop:
    - kubelet.conf
    - 20-etcd-service-manager.conf
  notify: restart kubelet

- name: Run pending handlers
  meta: flush_handlers

- name: Ensure kubelet is running
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: yes

- name: Install crictl for troubleshooting purposes
  ansible.builtin.apt:
    name: cri-tools
    state: present

# Install etcdctl

- name: Check if etcdctl is already been installed
  stat:
    path: /usr/local/bin/etcdctl
  register: etcdctl

- block:

  - name: Get latest version of etcd
    ansible.builtin.shell:
      cmd: curl -s https://api.github.com/repos/etcd-io/etcd/releases/latest | grep tag_name | cut -d '"' -f 4
    register: etcd_version

  - name: Download latest version etcd
    ansible.builtin.get_url:
      url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version.stdout | trim }}/etcd-{{ etcd_version.stdout | trim }}-linux-amd64.tar.gz"
      dest: "/tmp/etcd-{{ etcd_version.stdout | trim }}-linux-amd64.tar.gz"

  - name: Open archive
    ansible.builtin.unarchive:
      src: "/tmp/etcd-{{ etcd_version.stdout | trim }}-linux-amd64.tar.gz"
      dest: "/tmp"
      remote_src: true

  - name: Copy etcdctl binary to /usr/local/bin directory
    ansible.builtin.copy:
      src: "/tmp/etcd-{{ etcd_version.stdout | trim }}-linux-amd64/etcdctl"
      dest: /usr/local/bin/etcdctl
      mode: "0755"
      remote_src: yes

  when: not etcdctl.stat.exists

# 2. Create configuration files for kubeadm. Do this only on the first node.

- ansible.builtin.set_fact:
    etcd_names: "{{ groups['etcd_nodes'] }}"
    etcd_hosts: "{{ groups['etcd_nodes'] | map('extract', hostvars, 'ansible_host') | list }}"
    etcd_non_primary_names: "{{ groups['etcd_nodes'] | reject('search', inventory_hostname)}}"
    etcd_non_primary_hosts: "{{ groups['etcd_nodes'] | map('extract', hostvars, 'ansible_host') | list | reject('search', ansible_host)}}"
  run_once: true

- ansible.builtin.set_fact:
    names_to_hosts: "{{ names_to_hosts | default({}) | combine( {item: hostvars[item]['ansible_host']} ) }}"
  with_items:
    - "{{ groups['etcd_nodes'] }}"
  run_once: true

- name: Ensure temporary directories for each etcd cluster node configuration exits
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0775'
    recurse: true
  loop: "{{ etcd_hosts }}"
  run_once: true

- name: Create kubeadm configuration files for each etcd cluster node
  ansible.builtin.template:
    src: kubeadm_config.j2
    dest: "/tmp/{{ item }}/kubeadmcfg.yaml"
  loop: "{{ etcd_hosts }}"
  loop_control:
    index_var: idx
  run_once: true

# 3. Generate the certificate authority. Do this only on the first node.

- name: Generate the certificate authority
  ansible.builtin.command:
    cmd: kubeadm init phase certs etcd-ca
    creates: /etc/kubernetes/pki/etcd/ca.crt
  run_once: true

- name: Check if certficates have already been generated
  stat:
    path: /etc/kubernetes/pki/etcd/server.crt
  register: server_cert

- block:

  # 4. Create certificates for each member. Do this only on the first node.

  - name: Create certificates for other nodes
    ansible.builtin.include_tasks: create_host_certificates.yaml
    loop: "{{ etcd_non_primary_hosts }}"
    loop_control:
      loop_var: current_host
    run_once: true

  - name: Create certificates for primary node
    ansible.builtin.command:
      cmd: "{{ item }}"
    loop:
      - "kubeadm init phase certs etcd-server --config=/tmp/{{ ansible_host }}/kubeadmcfg.yaml"
      - "kubeadm init phase certs etcd-peer --config=/tmp/{{ ansible_host }}/kubeadmcfg.yaml"
      - "kubeadm init phase certs etcd-healthcheck-client --config=/tmp/{{ ansible_host }}/kubeadmcfg.yaml"
      - "kubeadm init phase certs apiserver-etcd-client --config=/tmp/{{ ansible_host }}/kubeadmcfg.yaml"
    run_once: true

  - name: Clean up certs that should not be copied off this host
    ansible.builtin.command:
      cmd: "find /tmp/{{ item }} -name ca.key -type f -delete"
      removes: "/tmp/{{ item }}/pki/etcd/ca.key"
    loop: "{{ etcd_non_primary_hosts }}"
    run_once: true

  - name: Change permissions on temp directories/remote/file/path to ansible:user so we can write to it
    ansible.builtin.file:
      path: "/tmp/{{ item }}/"
      owner: vagrant
      group: vagrant
      mode: '0775'
      recurse: true
    loop: "{{ etcd_hosts }}"
    run_once: true

  # 5. Copy certificates and kubeadm configs. Do this only on the first node.

  - name: Create temporary directories on localhost for each non-primary etcd node
    become: false
    ansible.builtin.file:
      path: "/tmp/{{ item }}"
      state: directory
    loop: "{{ etcd_non_primary_hosts }}"
    delegate_to: localhost
    run_once: true

  - name: Copy certs and kubeadm configs for non-primary etcd nodes to localhost from primary etcd node
    become: false
    ansible.posix.synchronize:
      src: "/tmp/{{ item }}/"
      dest: "/tmp/{{ item }}/"
      mode: pull
      private_key: "{{ ansible_ssh_private_key_file }}"
    loop: "{{ etcd_non_primary_hosts }}"
    run_once: true

  - name: Copy certs and kubeadm configs from localhost to non-primary etcd nodes
    ansible.builtin.copy:
      src: "/tmp/{{ names_to_hosts[item] }}/"
      dest: "/tmp/{{ names_to_hosts[item] }}/"
    delegate_to: "{{ item }}"
    loop: "{{ etcd_non_primary_names }}"
    run_once: true

  - name: Copy certs from /tmp/ to /etc/kubernetes directory in non-primary etcd nodes
    ansible.builtin.copy:
      src: "/tmp/{{ names_to_hosts[item] }}/pki"
      dest: "/etc/kubernetes/"
    delegate_to: "{{ item }}"
    loop: "{{ etcd_non_primary_names }}"
    run_once: true

  - name: Delete certs and kubeadm configs directories from localhost /tmp
    ansible.builtin.file:
      path: "/tmp/{{ item }}"
      state: absent
    loop: "{{ etcd_non_primary_hosts }}"
    delegate_to: localhost
    run_once: true

  when: not server_cert.stat.exists

# 6. Ensure all expected files exist.
# 7. Create the static pod manifests.

- name: Create the static pod manifests in all etcd cluster nodes
  ansible.builtin.command:
    cmd: "kubeadm init phase etcd local --config=/tmp/{{ names_to_hosts[item] }}/kubeadmcfg.yaml"
    creates: /etc/kubernetes/manifests/etcd.yaml
  delegate_to: "{{ item }}"
  loop: "{{ groups['etcd_nodes'] }}"
  run_once: true

# 8. Optional: Check the cluster health.
