---
- name: Dynamic Kubernetes Target Infrastructure Setup
  hosts: localhost
  gather_facts: false
  vars:
    jenkins_agent_namespace: "jenkins-agents"
    pod_names:
      - ansible-target-1
      - ansible-target-2
      - ansible-target-3

  tasks:
    - name: Spin up 3 target pods
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{ item }}"
            namespace: "{{ jenkins_agent_namespace }}"
            labels:
              app: "ansible-test-target-{{ item }}"
          spec:
            containers:
              - name: target
                image: bobfleming/ansible-host:0.0.2
                command: ["/bin/sh", "-c", "while true; do sleep 30; done"] # Keep pod alive
        state: present
      loop: "{{ pod_names }}"

    - name: Wait for pods to be running and ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ jenkins_agent_namespace }}"
        name: "{{ item }}"
      register: pod_info
      until: "pod_info.resources | length > 0 and pod_info.resources[0].status.phase == 'Running'"
      retries: 20
      delay: 5
      loop: "{{ pod_names }}"

    - name: Expose ports on target pods
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ item }}-svc"
            namespace: "{{ jenkins_agent_namespace }}"
          spec:
            selector:
              app: "ansible-test-target-{{ item }}"
            ports:
              - name: etcd-client
                protocol: TCP
                port: 2379
                targetPort: 2379
              - name: etcd-peer
                protocol: TCP
                port: 2380
                targetPort: 2380
        state: present
      loop: "{{ pod_names }}"

    - name: Get service IP addresses
      kubernetes.core.k8s_info:
        kind: Service
        namespace: "{{ jenkins_agent_namespace }}"
        name: "{{ item }}-svc"
      register: svc_info
      loop: "{{ pod_names }}"

    - name: Create mappng for pod name to service IPs
      ansible.builtin.set_fact:
        pod_to_ip_map: "{{ pod_to_ip_map | default({}) | combine({item.item: item.resources[0].spec.clusterIP}) }}"
      loop: "{{ svc_info.results }}"

    - name: Print out mapping
      ansible.builtin.debug:
        var: pod_to_ip_map

    - name: Dynamically add pods to the Ansible in-memory inventory
      ansible.builtin.add_host:
        name: "{{ item }}"
        ansible_connection: kubernetes.core.kubectl
        ansible_kubernetes_namespace: "{{ jenkins_agent_namespace }}"
        ansible_kubernetes_container: target
        ansible_python_interpreter: /usr/bin/python3.14
        ansible_kubectl_pod: "{{ item }}"
        ansible_host: "{{ pod_to_ip_map[item] }}"
        groups: dynamic_targets
      loop: "{{ pod_names }}"

    - name: Print out all vars for dynamic_targets group
      ansible.builtin.debug:
        msg: "{{ hostvars[item] }}"
      loop: "{{ pod_names }}"

- name: Run Playbook Tests Against Dynamic Pods
  hosts: dynamic_targets
  gather_facts: false
  become: true

  tasks:
    - name: Test raw command inside the Kubernetes pod
      ansible.builtin.raw: hostname
      changed_when: false

    - name: Test command plugin inside the Kubernetes pod
      ansible.builtin.command: hostname
      changed_when: false

    - name: Test shell plugin inside the Kubernetes pod
      ansible.builtin.shell: >
        hostname
      changed_when: false

    - name: Test apt plugin inside the Kubernetes pod
      ansible.builtin.apt:
        name: nginx
        state: present

- name: Teardown Infrastructure
  hosts: localhost
  gather_facts: false
  tags: [teardown]
  vars:
    jenkins_agent_namespace: "jenkins-agents"
    pod_names: [ansible-target-1, ansible-target-2, ansible-target-3]
  tasks:
    - name: Destroy the 3 target pods
      kubernetes.core.k8s:
        kind: Pod
        namespace: "{{ jenkins_agent_namespace }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ pod_names }}"

    - name: Delete services
      kubernetes.core.k8s:
        kind: Service
        namespace: "{{ jenkins_agent_namespace }}"
        name: "{{ item }}-svc"
        state: absent
      loop: "{{ pod_names }}"
