---
- name: Install and setup HAProxy on loadbalancer
  hosts: lb_node
  become: true
  tags: [lb]

  vars_files:
    - k8s_vars.yaml

  roles:
    - role: lb_setup
    - role: install_helm
      when: lb_setup_install_kubectl

- name: Install containerd cri, kubeadm, kubelet and kubectl to all nodes in cluster
  hosts: k8s_cluster
  become: true
  tags: [setup]

  vars_files:
    - k8s_vars.yaml

  roles:
    - role: containerd
      when: install_containerd | default(true) | bool
    - role: kubeadm
    - role: setup_ssh_keys_between_hosts
      setup_ssh_keys_between_hosts_for_ansible_user: true
      setup_ssh_keys_between_hosts_for_root: false

- name: Setup external etcd cluster
  hosts: etcd_nodes
  become: true
  tags: [etcd]

  vars_files:
    - k8s_vars.yaml

  roles:
    - setup_etcd_cluster

- name: Initialize first control plane node and install cni
  hosts: control_plane_nodes[0]
  become: true
  tags: [init_cluster]

  vars_files:
    - k8s_vars.yaml

  roles:
    - role: init_cluster
    - role: cilium
      when: install_cilium | default(true) | bool
    - role: install_helm

- name: Join the rest of the control plane nodes to cluster
  hosts: control_plane_nodes[1:]
  become: true
  tags: [join_control]

  vars_files:
    - k8s_vars.yaml

  roles:
    - role: join_control

- name: Join all worker nodes to cluster
  hosts: worker_nodes
  become: true
  tags: [join_worker]

  vars_files:
    - k8s_vars.yaml

  roles:
    - join_worker

- name: Extra configuration for control plane nodes
  hosts: control_plane_nodes
  become: true
  tags: [extra_control_plane]

  vars_files:
    - k8s_vars.yaml

  roles:
    - role: encrypt_etcd_at_rest
      when: encrypt_etcd_at_rest_encrypt_etcd | default(false) | bool

- name: Extra configuration for worker nodes
  hosts: worker_nodes
  become: true
  tags: [extra_worker]

  vars_files:
    - k8s_vars.yaml

- name: Extra configuration for all cluster nodes
  hosts: k8s_cluster
  become: true
  tags: [extra_cluster]

  vars_files:
    - k8s_vars.yaml

  roles:
    - role: gvisor
      when: install_gvisor | default(false) | bool
    - role: request_kubelet_serving_cert
