# containerd variables
install_containerd: true
containerd_cni_plugins_version: "v1.9.1"
containerd_crictl_version: "v1.36.0"
containerd_cni_plugins_target_dir: "/opt/cni/bin"
containerd_sandbox_image: "registry.k8s.io/pause:3.10.1"
containerd_service: "containerd"

# kubernetes variables
kubeadm_kubernetes_version: "v1.36"
init_cluster_pod_network_cidr: "10.100.0.0/16"
init_cluster_service_network_cidr: "10.44.0.0/16"
init_cluster_apiserver_cert_extra_sans: []
init_cluster_skip_kube_proxy: true

# cilium cni variables
install_cilium: true
cilium_cli_target_dir: "/usr/local/bin"

# loadbalancer variables
lb_setup_install_kubectl: true # install kubectl on loadbalancer
init_cluster_setup_kubeconfig_on_lb: true # set .kube/config on loadbalancer

# etcd variables
etcd_cert_dir: "/tmp/etcd_cert"

# encrypt etcd at rest
encrypt_etcd_at_rest_encrypt_etcd: true
encrypt_etcd_at_rest_apiserver_timeout: 60
encrypt_etcd_at_rest_encrypted_resources:
  - secrets
encrypt_etcd_at_rest_encryption_providers:
  - secretbox:
      keys:
        - name: key1
          secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
  - identity: {}

# extra software: gvisor variables
install_gvisor: true
gvisor_runsc_target_dir: "/usr/local/bin"
gvisor_runsc_dirs:
  - "/usr/local/bin"
  - "/usr/bin"
gvisor_url: "https://storage.googleapis.com/gvisor/releases/release/latest"
gvisor_containerd_config: "/etc/containerd/config.toml"
