# containerd variables
install_containerd: true
cni_plugins_version: "v1.9.1"
cni_plugins_target_dir: "/opt/cni/bin"
containerd_sandbox_image: "registry.k8s.io/pause:3.10.1"
containerd_service: "containerd"

# kubernetes variables
kubernetes_version: "v1.36"
pod_network_cidr: "10.100.0.0/16"
service_network_cidr: "10.44.0.0/16"
apiserver_cert_extra_sans: []
skip_kube_proxy: true

# cilium cni variables
install_cilium: true
cilium_cli_target_dir: "/usr/local/bin"

# loadbalancer variables
install_kubectl: true # install kubectl on loadbalancer
setup_kubeconfig_on_lb: true # set .kube/config on loadbalancer

# extra software: gvisor variables
install_gvisor: true
runsc_target_dir: "/usr/local/bin"
runsc_dirs:
  - "/usr/local/bin"
  - "/usr/bin"
gvisor_url: "https://storage.googleapis.com/gvisor/releases/release/latest"
containerd_config: "/etc/containerd/config.toml"
