LOAD_BALANCER = ENV['LOAD_BALANCER'] || 1
ETCD_NODES = ENV['ETCD_NODES'] || 3
CONTROL_PLANE_NODES = ENV['CONTROL_PLANE_NODES'] || 3
WORKER_NODES = ENV['WORKER_NODES'] || 3

Vagrant.configure("2") do |config|

    # ====================== GLOBAL SETTINGS ======================
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # ====================== VIRTUALBOX PROVIDER HARDENING ======================
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true

     # Force ALL VMs to use the same reliable adapter
    vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet0"]
    vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
  end

  if Integer(LOAD_BALANCER) == 1
    config.vm.define "lb" do |lb|
      lb.vm.box = "cloud-image/ubuntu-24.04"
      lb.vm.hostname = "lb"
      lb.vm.network "private_network", ip: "192.168.59.20"
      lb.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
    end
  end

  (1..Integer(ETCD_NODES)).each do |i|
    config.vm.define "etcd-#{i}" do |etcd|
      etcd.vm.box = "cloud-image/ubuntu-24.04"
      etcd.vm.hostname = "etcd-#{i}"
      etcd.vm.network "private_network", ip: "192.168.59.#{10 + i - 1}"
      etcd.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    end
  end
    
  (1..Integer(CONTROL_PLANE_NODES)).each do |i|
    config.vm.define "control-#{i}" do |control|
      control.vm.box = "generic/ubuntu2204"
      control.vm.hostname = "control-#{i}"
      control.vm.network "private_network", ip: "192.168.59.#{30 + i - 1}"
      control.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
    end
  end

  (1..Integer(WORKER_NODES)).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.hostname = "worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.59.#{50 + i - 1}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
    end
  end
end
