LOAD_BALANCER = ENV['LOAD_BALANCER'] || 1
CONTROL_PLANE_NODES = ENV['CONTROL_PLANE_NODES'] || 3
WORKER_NODES = ENV['WORKER_NODES'] || 2

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = true
    config.vbguest.installer_options = { allow_kernel_headers: true }
  end

  if Integer(LOAD_BALANCER) == 1
    config.vm.define "lb" do |lb|
      lb.vm.box = "generic/ubuntu2204"
      lb.vm.hostname = "lb"
      lb.vm.network "private_network", ip: "192.168.56.10"
      lb.ssh.insert_key = false
      lb.vm.synced_folder ".", "/vagrant", disabled: true
      lb.vm.provider "virtualbox" do |vb|
        vb.memory = "1048"
        vb.linked_clone = true
      end
    end
  end

  (1..Integer(CONTROL_PLANE_NODES)).each do |i|
    config.vm.define "control-#{i}" do |control|
      control.vm.box = "generic/ubuntu2204"
      control.vm.hostname = "control-#{i}"
      control.vm.network "private_network", ip: "192.168.57.#{i + 9}"
      control.ssh.insert_key = false
      control.vm.synced_folder ".", "/vagrant", disabled: true
      control.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.linked_clone = true
      end
    end
  end

  (1..Integer(WORKER_NODES)).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.hostname = "worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.58.#{i + 9}"
      worker.ssh.insert_key = false
      worker.vm.synced_folder ".", "/vagrant", disabled: true
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.linked_clone = true
      end
    end
  end
end
