LOAD_BALANCER = ENV['LOAD_BALANCER'] || 0
ETCD_NODES = ENV['ETCD_NODES'] || 3
CONTROL_PLANE_NODES = ENV['CONTROL_PLANE_NODES'] || 0
WORKER_NODES = ENV['WORKER_NODES'] || 0

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.installer_options = { allow_kernel_headers: true }
  end

  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    # Force the second NIC to use a consistent host-only adapter
    vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet5"]
  end

  if Integer(LOAD_BALANCER) == 1
    config.vm.define "lb" do |lb|
      lb.vm.box = "cloud-image/ubuntu-24.04"
      lb.vm.hostname = "lb"
      lb.vm.network "private_network", ip: "192.168.56.10"
      lb.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
    end
  end

  (1..Integer(ETCD_NODES)).each do |i|
    config.vm.define "etcd-#{i}" do |etcd|
      etcd.vm.box = "cloud-image/ubuntu-24.04"
      etcd.vm.hostname = "etcd-#{i}"
      etcd.vm.network "private_network", ip: "192.168.59.#{i + 9}"
      etcd.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    end
  end
    
  (1..Integer(CONTROL_PLANE_NODES)).each do |i|
    config.vm.define "control-#{i}" do |control|
      control.vm.box = "generic/ubuntu2204"
      control.vm.hostname = "control-#{i}"
      control.vm.network "private_network", ip: "192.168.57.#{i + 9}"
      control.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
    end
  end

  (1..Integer(WORKER_NODES)).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.hostname = "worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.58.#{i + 9}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
    end
  end
end
