---
# - name: Get kubelet config file
#   ansible.builtin.shell:
#     cmd: set -o pipefail && ps -ef | grep '[k]ubelet' | grep -oP -- '--config=\K\S+'
#   register: request_kubelet_serving_cert_kubelet_config
#   changed_when: kubelet_config.rc != 0

- name: Get primary control plane node
  ansible.builtin.set_fact:
    request_kubelet_serving_cert_primary_control_plane_node: "{{ groups['control_plane_nodes'] | first | default('') }}"

- name: Get kubelet config file
  ansible.builtin.command:
    cmd: ps -ef
  register: request_kubelet_serving_cert_ps_output
  changed_when: false

- name: Extract kubelet config path
  ansible.builtin.set_fact:
    request_kubelet_serving_cert_kubelet_config_path: >-
      {{ (request_kubelet_serving_cert_ps_output.stdout
          | regex_findall('kubelet.*--config=([^\s]+)'))
          | first
          | default('') }}

- name: Add serverTLSBootstrap with value true to kubelet config
  ansible.builtin.lineinfile:
    state: present
    dest: "{{ request_kubelet_serving_cert_kubelet_config_path }}"
    line: "serverTLSBootstrap: true"
    regexp: "^serverTLSBootstrap: true"
  notify:
    - restart kubelet
    - approve pending csr
  register: request_kubelet_serving_cert_config_result

- name: Ensure kubelet is restarted immediately
  ansible.builtin.meta: flush_handlers
